config/routes.rb
Rails.application.routes.draw do
  devise_for :restaurant_admins
  devise_for :diners
  get '/' => 'landing_pages#landing'
  ###################################################
  get '/logins' => 'log_ins#index'
  ###################################################
  get '/theme' => 'theme#index'
  ###################################################
  get '/restaurants' => 'restaurants#index'
  get '/restaurants/available' => 'restaurants#available'
  get '/restaurants/new' => 'restaurants#new'
  post '/restaurants' => 'restaurants#create'
  get '/restaurants/:id' => 'restaurants#show'
  get '/restaurants/:id/edit' => 'restaurants#edit'
  patch '/restaurants/:id' => 'restaurants#update'
  delete '/restaurants/:id' => 'restaurants#destroy'
  post '/search' => 'restaurants#run_search'
  ###################################################
  get '/reservations' => 'reservations#index'
  get '/reservations/new' => 'reservations#new'
  post '/reservations' => 'reservations#create'
  get '/reservations/:id' => 'reservations#show'
  delete '/reservations/:id' => 'reservations#destroy'
  ###################################################
  get '/timeslots/:id' => 'timeslots#show'

  namespace :api do
    namespace :v1 do
      get '/restaurants' => 'restaurants#index'
      get '/restaurants/:id' => 'restaurants#show'
      get '/reservations' => 'reservations#index'
      get '/reservations/:id' => 'reservations#show'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>DINE.</title>

        <!-- Bootstrap -->
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <!-- font awesome for icons -->
        <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- flex slider css -->
        <link href="/css/flexslider.css" rel="stylesheet" type="text/css" media="screen">
        <!-- animated css  -->
        <link href="/css/animate.css" rel="stylesheet" type="text/css" media="screen"> 
        <!-- Revolution Style-sheet -->
        <link rel="stylesheet" type="text/css" href="/rs-plugin/css/settings.css">
        <link rel="stylesheet" type="text/css" href="/css/rev-style.css">
        <!--owl carousel css-->
        <link href="/css/owl.carousel.css" rel="stylesheet" type="text/css" media="screen">
        <link href="/css/owl.theme.css" rel="stylesheet" type="text/css" media="screen">
        <!--mega menu -->
        <link href="/css/yamm.css" rel="stylesheet" type="text/css">
        <!--cube css-->
        <link href="/cubeportfolio/css/cubeportfolio.min.css" rel="stylesheet" type="text/css">
        <!-- custom css-->
        <link href="/css/style.css" rel="stylesheet" type="text/css" media="screen">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="/https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="/https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="top-bar-dark">            
            <div class="container">
                <div class="col-sm-12 text-right">
                    <ul class="list-inline top-dark-right">
                        <% if current_diner %>
                            <li><%= current_diner.email %></li>
                            <li><i class="fa fa-times"></i><%= link_to "Sign Out", "/diners/sign_out", method: :delete %><li>
                        <% elsif current_restaurant_admin %>
                            <li><%= current_restaurant_admin.email %></li>
                            <li><i class="fa fa-times"></i><%= link_to "Sign Out", "/restaurant_admins/sign_out", method: :delete %><li>
                        <% else %>
                            <li>RESTAURANT?</li>
                            <li><a href="/restaurant_admins/sign_in"><i class="fa fa-user"></i>Sign In</a></li>
                            <li><a href="/restaurant_admins/sign_up"><i class="fa fa-user-plus"></i>Sign Up</a></li>
                            <li>DINER?</li>
                            <li><a href="/diners/sign_in"><i class="fa fa-user"></i>Sign In</a></li>
                            <li><a href="/diners/sign_up"><i class="fa fa-user-plus"></i>Sign Up</a></li> 
                        <% end %>                  
                    </ul>
                </div>
            </div>
        </div><!--top-bar-dark end here-->
        <!--navigation -->
        <!-- Static navbar -->
        <div class="navbar navbar-default navbar-static-top yamm sticky" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="/img/logo.png" alt="DINE."></a>
                </div>
                <% if current_diner %>
                    <form class="navbar-form navbar-left" role="search">
                        <%= form_tag "/search", method: :post do %>
                        <%= label_tag :search, ""%>
                        <%= text_field_tag :search, nil, placeholder: "Restaurant, City, Zip", :class => "form-control" %>
                        <%= submit_tag "Search", :class => "btn btn-info" %>
                        <% end %>
                    </form>
                <% end %>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/restaurants">View All Restaurants</a></li>
                       <% if current_diner %>
                            <li><a href="/">Search for Restaurants With Availability</a></li>
                        <% end %>
                        <li id="maindropdown" class="dropdown active ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
                            <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                                <% if current_restaurant_admin %>
                                    <li><a href="/restaurants/new">Add New Restaurant</a></li>
                                    <li><a href="/restaurant_admins/edit">Edit Profie</a></li>
                                <% end %>
                                <% if current_diner %>
                                    <li><a href="/reservations">View All Reservations</a></li>
                                    <li><a href="/diners/edit">Edit Profie</a></li>
                                <% end %>
                            </ul>
                        </li>
                    
                        <!--                        <li class="dropdown">
                                                    <a href="#" class=" dropdown-toggle" data-toggle="dropdown"><i class="fa fa-lock"></i> Sign In</a>
                                                    <div class="dropdown-menu dropdown-menu-right dropdown-login-box animated fadeInUp">
                                                        <form role="form">
                                                            <h4>Signin</h4>
                        
                                                            <div class="form-group">
                                                                <div class="input-group">
                                                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                                                    <input type="text" class="form-control" placeholder="Username">
                                                                </div>
                                                                <br>
                                                                <div class="input-group">
                                                                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                                                    <input type="password" class="form-control" placeholder="Password">
                                                                </div>
                                                                <div class="checkbox pull-left">
                                                                    <label>
                                                                        <input type="checkbox"> Remember me
                                                                    </label>
                                                                </div>
                                                                <a class="btn btn-theme-bg pull-right">Login</a>
                                                                                                        <button type="submit" class="btn btn-theme pull-right">Login</button>                 
                                                                <div class="clearfix"></div>
                                                                <hr>
                                                                <p>Don't have an account! <a href="#">Register Now</a></p>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </li> menu login li end here-->
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--container-->
        </div><!--navbar-default-->


        
        <div class=container>
            <% flash.each do |name, message| %>
                <div class="alert alert-<%= name %> alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</span><span class="sr-only">Close</span></button>
                    <%= message.html_safe %>  
                </div>
            <% end %>
            <div class=container>
                <%= yield %>
            </div>
        </div>
        </body>
        <!--rev slider start-->


        <footer id="footer">
            
        </footer><!--default footer end here-->

        <!--scripts and plugins -->
        <!--must need plugin jquery-->
        <script src="/js/jquery.min.js"></script>
        <script src="/js/jquery-migrate.min.js"></script> 
        <!--bootstrap js plugin-->
        <script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>       
        <!--easing plugin for smooth scroll-->
        <script src="/js/jquery.easing.1.3.min.js" type="text/javascript"></script>
        <!--sticky header-->
        <script type="text/javascript" src="/js/jquery.sticky.js"></script>
        <!--flex slider plugin-->
        <script src="/js/jquery.flexslider-min.js" type="text/javascript"></script>
        <!--parallax background plugin-->
        <script src="/js/jquery.stellar.min.js" type="text/javascript"></script>

        <script src="/js/jquery.isotope.min.js" type="text/javascript"></script>
        <!--digit countdown plugin-->
        <script src="/js/waypoints.min.js"></script>
        <!--digit countdown plugin-->
        <script src="/js/jquery.counterup.min.js" type="text/javascript"></script>
        <!--on scroll animation-->
        <script src="/js/wow.min.js" type="text/javascript"></script> 
        <!--owl carousel slider-->
        <script src="/js/owl.carousel.min.js" type="text/javascript"></script>
        <!--popup js-->
        <script src="/js/jquery.magnific-popup.min.js" type="text/javascript"></script>
        <!--you tube player-->
        <script src="/js/jquery.mb.YTPlayer.min.js" type="text/javascript"></script> 
        <!--image loads plugin -->
        <script src="/js/jquery.imagesloaded.min.js" type="text/javascript"></script>       
        <!--customizable plugin edit according to your needs-->
        <script src="/js/custom.js" type="text/javascript"></script>
        <script src="/js/isotope-custom.js" type="text/javascript"></script>
        <script type="text/javascript" src="/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
        <script type="text/javascript" src="/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
        <script type="text/javascript" src="/js/revolution-custom.js"></script>
        <!--cube portfolio plugin-->
        <script src="/cubeportfolio/js/jquery.cubeportfolio.min.js" type="text/javascript"></script>
        <script src="/js/cube-portfolio.js" type="text/javascript"></script>
        <script src="/js/pace.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            var toggleOpen = function() {
                document.getElementById('maindropdown').
            }
        </script>
    </body>
</html>